version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "3030:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --sql_mode=""
    restart: unless-stopped
    tty: true
    ports:
      - "4307:3306"
    volumes:
      - ./init/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_DATABASE: reportdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: the$$32wasking
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
